// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIg78r_cuokV1mDqmqhFXifEVbWy_OA28',
    appId: '1:68288405858:web:c847a546d42824fea68c3b',
    messagingSenderId: '68288405858',
    projectId: 'godseye-91d7b',
    authDomain: 'godseye-91d7b.firebaseapp.com',
    storageBucket: 'godseye-91d7b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvG2TJp9QEXft2ycv3iXGNb_mHQGgZxd8',
    appId: '1:68288405858:android:51b440c5b452fa3fa68c3b',
    messagingSenderId: '68288405858',
    projectId: 'godseye-91d7b',
    storageBucket: 'godseye-91d7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD7lCMCygH6CD0VYFNmoeRELxUwl1i1y0',
    appId: '1:68288405858:ios:dfe826462bfb6599a68c3b',
    messagingSenderId: '68288405858',
    projectId: 'godseye-91d7b',
    storageBucket: 'godseye-91d7b.appspot.com',
    iosClientId: '68288405858-5malo1dhc3t0h78osp8i48ue1tctev3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.godseye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD7lCMCygH6CD0VYFNmoeRELxUwl1i1y0',
    appId: '1:68288405858:ios:dfe826462bfb6599a68c3b',
    messagingSenderId: '68288405858',
    projectId: 'godseye-91d7b',
    storageBucket: 'godseye-91d7b.appspot.com',
    iosClientId: '68288405858-5malo1dhc3t0h78osp8i48ue1tctev3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.godseye',
  );
}
